# Generated by Django 2.2.5 on 2019-10-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20191026_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='hotel',
        ),
    ]
