# Generated by Django 2.2.5 on 2019-10-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20191026_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='hotel.Room'),
        ),
    ]
