# Generated by Django 2.2.5 on 2019-11-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20191030_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.FileField(blank=True, default='default.png', upload_to=''),
        ),
    ]
