# Generated by Django 2.2.5 on 2019-11-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_city_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
