# Generated by Django 2.2.5 on 2019-11-03 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20191103_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='hotel.Room'),
        ),
    ]
