# Generated by Django 2.2.5 on 2019-11-03 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_option_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='room',
        ),
    ]
